name: Build OpenJDK 25 for Android

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 */2 *"

jobs:
  build_android:
    strategy:
      matrix:
        arch: [aarch64]
        version: [25]
      fail-fast: false

    name: "Build Java ${{ matrix.version }} for Android ${{matrix.arch}}"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 1.${{ matrix.version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          distribution: temurin

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt -y install autoconf python3 python-is-python3 unzip zip systemtap-sdt-dev libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev

      - name: Install clang 18 (LLVM apt repo)
        run: |
          sudo apt update
          sudo apt -y install wget gnupg lsb-release software-properties-common
          wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 18
          echo "CC=clang-18" >> $GITHUB_ENV
          echo "CXX=clang++-18" >> $GITHUB_ENV
          echo "LD=lld-18" >> $GITHUB_ENV
          clang-18 --version
          clang++-18 --version
          lld-18 --version
          
      - name: Build with CI build script
        run: export TARGET_VERSION=${{ matrix.version }} && bash "1_ci_build_arch_${{matrix.arch}}.sh"

      - name: Upload JDK build output
        uses: actions/upload-artifact@v4
        with:
          name: "jdk${{ matrix.version }}-${{matrix.arch}}"
          path: jdk${{ matrix.version }}*.tar.xz

      - name: Upload JRE build output
        uses: actions/upload-artifact@v4
        with:
          name: "jre${{ matrix.version }}-${{matrix.arch}}"
          path: jre${{ matrix.version }}*.tar.xz

      - name: Upload JRE debuginfo build output
        uses: actions/upload-artifact@v4
        with:
          name: "jre${{ matrix.version }}-debuginfo-${{matrix.arch}}"
          path: dizout
          
  pojav:
    needs: build_android
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [25]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Get jre${{ matrix.version }}-aarch64
        uses: actions/download-artifact@v4
        with:
          name: jre${{ matrix.version }}-aarch64
          path: pojav

      - name: Repack JRE
        run: export TARGET_VERSION=${{ matrix.version }} && bash "9_repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre${{ matrix.version }}-pojav

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jre${{ matrix.version }}-pojav
          path: pojav/jre${{ matrix.version }}-pojav/*
